//this file is part of notepad++
//Copyright (C)2012 Austin Young ( pattazl@gmail.com )
//
//This program is free software; you can redistribute it and/or
//modify it under the terms of the GNU General Public License
//as published by the Free Software Foundation; either
//version 2 of the License, or (at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.
//
//You should have received a copy of the GNU General Public License
//along with this program; if not, write to the Free Software
//Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

#ifndef SelfCtrl_INCLUDED
#define SelfCtrl_INCLUDED

#include <windows.h>
#include "Window.h"

/* XOR mask for hand cursor */
/* Generated by HexEdit */
#define DefaultColor 0x86c2ff
#define DefaultSaveColor 0xb5ffb5
extern long MarkColor;
extern long SaveColor;
const int _MARK_INDEX = 10; //设置背景色
const int _SAVE_INDEX = 11; //设置保存背景色
const int STATE_SAVE = (1<<_SAVE_INDEX); // 保存的标识
extern HWND curScintilla;
#define SCI_MARKERSETBACK 2042

class SelfCtrl : public Window 
{
public:
    void create(HWND itemHandle, long IDIndex, long bkColor = DefaultColor);

    void destroy() {
	    if(_hCursor)
            ::DestroyCursor(_hCursor);
    };

	long GetColor() {
		return _bkColor;
	};

private :
    HCURSOR			_hCursor=0;
    WNDPROC			_oldproc=NULL;
    COLORREF		_bkColor;	
    bool			_clicking=false;
	long			SelfID;

    static LRESULT CALLBACK SelfCtrlProc(HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam) {
        return ((SelfCtrl *)(::GetWindowLongPtr(hwnd, GWLP_USERDATA)))->runProc(hwnd, Message, wParam, lParam);
    };

    LRESULT runProc(HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam);

	void SetTextBkColor(HWND hwnd);
};

#endif //SelfCtrl_INCLUDED
